feat: #11 Add AppBar Component
depromeet/layer pull request #24
Opened 2024-07-09 00:51 UTC by sean2337

> ### App Bar Component 개발 
---

### 🏄🏼‍♂️‍ Summary (요약)

- App Bar 컴포넌트 개발
- 뒤로가기 구현

### 🫨 Describe your Change (변경사항)

- /src/component/AppBar/AppBar.tsx

### 🧐 Issue number and link (참고)

- #11 

### 📚 Reference (참조)

- 헤더마다 왼쪽, 오른쪽 컴포넌트가 재각각 달라 AppBar에서 해당 컴포넌트를 제작하는 것보단, 그 페이지마다에서 개발을 진행한 후 그 자체 컴포넌트를 props로 받아서 보여주는게 맞다고 판단했습니다.
따라서 다음과 같은 Props를 받습니다.
- Props
1. children?: React.ReactNode => AppBar에 들어갈 제목
2. visible?: boolean => true(default): 헤더가 보여짐, false: 헤더 제거
3. LeftComp?: React.ReactNode => 왼쪽에 보여질 컴포넌트 default(뒤로가기)
4. RightComp?: React.ReactNode => 오른쪽에 보여질 컴포넌트

-사용 예시
```js
<AppBar RightComp={<>Right Comp</>}>
        의미없는 제목
</AppBar>
```

- 사용 결과
<img width="402" alt="image" src="https://github.com/depromeet/layer/assets/100525337/d1eb216a-0fe3-4cb4-b33d-a51b19644113">

2024-07-09 03:30 UTC, klmhyeonwoo commented
늦은 머지 죄송합니다!
혹시 제 커밋 반영해서 반영까지 같이 넣어주실 수 있으실까요~?

2024-07-13 07:40 UTC, leeminhee119 approved these changes
👍 👍 고생하셨습니다!

2024-07-13 07:40 UTC, leeminhee119 commented on src/layout/DefaultLayout.tsx
> +type DefaultLayoutProps = PropsWithChildren & AppBarProps;
앗 혹시 [PropsWithChildren에 제네릭 타입](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/813a8799e465a7d5f0d6776643f20f93681e85e4/types/react/index.d.ts#L820)을 지정하지 않아도 되나요 ??

2024-07-13 07:40 UTC, leeminhee119 commented on src/component/AppBar/AppBar.tsx
> +const AppBar = ({ title, appBarVisible = true, LeftComp = <Back />, RightComp = <div></div> }: AppBarProps) => {
잘 몰라서 여쭤봅니다! RightComp에는 기본값이 아무것도 없는 형태라 div 태그를 작성하신 거라면, div 대신 null 또는 빈 태그를 부여하면 어떻게 되나요 ??

2024-07-13 07:40 UTC, leeminhee119 commented on src/app/login/kakao/kakaoLogin.tsx
> +export function kakaoLogin() {
어랏 카멜로 작성돼있어요 (파일명도) ! 확인 부탁드려용

2024-07-13 10:34 UTC, sean2337 commented on src/component/AppBar/AppBar.tsx
> +const AppBar = ({ title, appBarVisible = true, LeftComp = <Back />, RightComp = <div></div> }: AppBarProps) => {
제가 의도한 형태는 `space between`을 적용해서 항상 title이 중앙에 오도록 개발했습니다. 
만약 null이나 <></> 이러한 태그를 넣게 될 경우 LeftComp가 왼쪽, Title이 오른쪽으로 가는 의도치 않은 형태가 되어 빈 div태그를 넣어서 RightComp를 넣지 않더라도 Title이 중앙에 오도록 하였습니다.

2024-07-13 10:48 UTC, sean2337 commented on src/layout/DefaultLayout.tsx
> +type DefaultLayoutProps = PropsWithChildren & AppBarProps;
제가 알기론, PropsWithChildren타입은 props로 children을 받을때 선언해주는걸로 알고 있는데 따로 제네릭 타입을 선정하는 이유가 있을까요?

2024-07-13 10:52 UTC, sean2337 commented on src/app/login/kakao/kakaoLogin.tsx
> +export function kakaoLogin() {
요거는 페이지는 아니구, 카카오 로그인에 필요한 로직 함수인데 이는 카멜이 맞지 않나요??

2024-07-13 11:22 UTC, leeminhee119 commented on src/layout/DefaultLayout.tsx
> +type DefaultLayoutProps = PropsWithChildren & AppBarProps;
옵셔널한 children 외의 props 타입들을 제네릭 타입에 지정해주는 걸로 이해하고 있습니다!

2024-07-13 11:22 UTC, leeminhee119 commented on src/component/AppBar/AppBar.tsx
> +const AppBar = ({ title, appBarVisible = true, LeftComp = <Back />, RightComp = <div></div> }: AppBarProps) => {
아하 ~ 그렇군요 이해했습니다!!

2024-07-13 11:27 UTC, leeminhee119 commented on src/app/login/kakao/kakaoLogin.tsx
> +export function kakaoLogin() {
아앗 컴포넌트가 아니군요! app 폴더 안에 있어서 컴포넌트라고 제가 착각했네요 하핫 😂

2024-07-13 12:08 UTC, sean2337 commented on src/layout/DefaultLayout.tsx
> +type DefaultLayoutProps = PropsWithChildren & AppBarProps;
아래와 같이 말씀하시는건가요?? 제가 정확히 이해한지 헷갈려서 여쭈어봐요!! 
```jsx
type DefaultLayoutProps = PropsWithChildren<AppBarProps>;
```

2024-07-13 12:14 UTC, leeminhee119 commented on src/layout/DefaultLayout.tsx
> +type DefaultLayoutProps = PropsWithChildren & AppBarProps;
앗 네네 맞아요 !!

2024-07-13 12:32 UTC, sean2337 commented on src/app/login/kakao/kakaoLogin.tsx
> +export function kakaoLogin() {
네넵 맞습니다. 기존에 만든것 또한 현재 컨벤션이랑 다른게 너무 많아 따로 이슈로 파두고 수정할 예정입니다!!
언급해주셔서 감사합니다 ☺️☺️

2024-07-13 13:28 UTC, leeminhee119 commented on src/app/login/kakao/kakaoLogin.tsx
> +export function kakaoLogin() {
저두 너무 많아서 브랜치 새로 파서 수정하려구요.. ㅎㅎ 좋습니다

2024-07-14 13:46 UTC, klmhyeonwoo requested changes

2024-07-14 13:46 UTC, klmhyeonwoo commented on src/layout/DefaultLayout.tsx
> +      <AppBar title={title} appBarVisible={appBarVisible} LeftComp={LeftComp} RightComp={RightComp} />
`DefaultLayout` 에서 `appBarVisible` props를 받은 후에, `DefaultLayout`에서 아래와 같이 처리를 할 수도 있을 것 같아요! 이렇게 하면 `<AppBar/>` 컴포넌트에서는 해당 컴포넌트에 필요한 `title`, `LeftComp`, `RightComp`만 넘길 수 있을 것 같아요! 한번 더 props를 넘기는 구조로 설계하신 의도가 따로 있으실까요?! 🤔
```suggestion
      {appBarVisible && <AppBar title={title} LeftComp={LeftComp} RightComp={RightComp} />}
```

2024-07-14 19:41 UTC, sean2337 commented on src/layout/DefaultLayout.tsx
> +      <AppBar title={title} appBarVisible={appBarVisible} LeftComp={LeftComp} RightComp={RightComp} />
처음에는 AppBar를 설계할때 Props를 저렇게 설계해놔서 다음과 같이 개발했고, DefaultLayout에 이를 넣으면서 `appBarVisible`을 AppBar에 Props로 넘겨주는게 좋을지, 현우님이 말씀하신 것처럼 하는게 좋을지 고민했었습니다!! 

이렇게 한 이유는 나중에 AppBar만 단독으로 쓰일때 appBarVisible를 쓰기 위한 확장성 때문이었습니다. 
하지만 듣고보니 현우님 말씀대로... 진행하는게 좋겠네요!!

2024-07-15 03:30 UTC, klmhyeonwoo approved these changes
고생하셨습니다 ✨

2024-07-15 04:26 UTC, donghunee approved these changes
수고하셨습니다:)

2024-07-15 04:36 UTC, merged